// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2aoi1tlaPgYIvaS0uRdRjGwBj2_-3Bc',
    appId: '1:157216180253:web:e28f817a084e0696589ef4',
    messagingSenderId: '157216180253',
    projectId: 'travelwishlist-1e39d',
    authDomain: 'travelwishlist-1e39d.firebaseapp.com',
    storageBucket: 'travelwishlist-1e39d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSouLbhmWWUljE8Fl6h2IulrhJRm0_cE',
    appId: '1:157216180253:android:4cd4da9c3422a5bc589ef4',
    messagingSenderId: '157216180253',
    projectId: 'travelwishlist-1e39d',
    storageBucket: 'travelwishlist-1e39d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1s42qLQVt-icGnWjfmSQ2Qks4GV4YDgk',
    appId: '1:157216180253:ios:4e22dba0f4212453589ef4',
    messagingSenderId: '157216180253',
    projectId: 'travelwishlist-1e39d',
    storageBucket: 'travelwishlist-1e39d.firebasestorage.app',
    iosBundleId: 'com.example.travelWishlist',
  );
}
